apiVersion: v1
kind: replicationcontroller
metadata:
 name: httpd
 labels:
  author: intelliqit
spec:
 replicas: 3
 template:
  metadata:
   name:
   labels:
    author: intelliqit
  spec: 
   containers:
    - name: myhttpd
      image:
      ports:
       - containerPort: 80
         hostPort: 8080