apiVersion: v1
kind: replicationcontroller
metadata:
 name: httpd
 labels:
  author: intelliqit
spec:
 replicas: 3
 template:
  metadata:
   name: httpd_pod
   labels:
    author: intelliqit
 spec: 
  containers:
   - name: myhttpd
     image: httpd 
     ports:
      - containerPort: 80
        hostPort: 8080